dist: trusty
sudo: required
language: node_js
node_js:
- 6

addons:
  apt:
    packages:
      - build-essential 
      - libmicrohttpd-dev
      - libjansson-dev
      - libnice-dev
      - libssl-dev
      - libsrtp-dev
      - libsofia-sip-ua-dev
      - libglib2.0-dev
      - libopus-dev
      - libogg-dev
      - libcurl4-openssl-dev
      - pkg-config
      - gengetopt
      - libtool
      - automake

before_script:
 - wget https://github.com/cisco/libsrtp/archive/v2.0.0.tar.gz
 - tar xfv v2.0.0.tar.gz
 - cd libsrtp-2.0.0
 - ./configure --prefix=/usr --enable-openssl
 - make shared_library && sudo make install
 - cd ..

script:
  - sh autogen.sh
  - ./configure
  - make
